from __future__ import annotations

from typing import Any


PERMISSIONS = [
    ("dashboard_view", "运行看板", "运行看板", "查看运行概览、报警和待处理工单"),
    ("chemical_query", "化学品查询", "数据查询", "查询化学品台账"),
    ("chemical_manage", "库存调整", "数据查询", "执行入库、出库等库存调整"),
    ("parameter_view", "参数查看", "参数监控", "查看实时参数和趋势"),
    ("parameter_ack", "报警确认", "参数监控", "确认报警信息"),
    ("parameter_config", "阈值配置", "参数监控", "修改参数报警阈值"),
    ("workorder_view", "工单查看", "工单管理", "查看工单台账"),
    ("workorder_create", "工单新建", "工单管理", "新建处理工单"),
    ("workorder_update", "工单更新", "工单管理", "编辑工单并流转状态"),
    ("workorder_close", "工单关闭", "工单管理", "关闭已完成工单"),
    ("workorder_delete", "工单删除", "工单管理", "删除工单"),
    ("report_preview", "报表预览", "报表导出", "生成报表预览"),
    ("report_export", "报表导出", "报表导出", "导出 CSV 报表"),
    ("audit_view", "审计查看", "系统管理", "查看操作审计日志"),
    ("user_manage", "用户管理", "系统管理", "维护用户账号"),
    ("role_manage", "角色权限", "系统管理", "配置角色权限"),
]

ROLES = [
    ("admin", "管理员", "系统管理员，拥有完整管理权限。", 1),
    ("operator", "普通操作员", "现场操作员，负责查询、监控和工单处理。", 1),
]

ROLE_PERMISSIONS = {
    "admin": [code for code, *_ in PERMISSIONS],
    "operator": [
        "dashboard_view",
        "chemical_query",
        "parameter_view",
        "workorder_view",
        "workorder_create",
        "workorder_update",
        "report_preview",
    ],
}

USERS = [
    ("admin", "admin123", "系统管理员", "admin", 1),
    ("operator", "operator123", "现场操作员", "operator", 1),
]


def default_data() -> dict[str, Any]:
    return {
        "chemicals": [
            {
                "id": "C001",
                "name": "甲醇",
                "category": "易燃液体",
                "storage_area": "A-01 原料罐区",
                "inventory": 1200.0,
                "unit": "L",
                "hazard_level": "高",
                "cas": "67-56-1",
                "supplier": "华东化工供应站",
                "updated_at": "2026-06-18 09:10:00",
            },
            {
                "id": "C002",
                "name": "氢氧化钠",
                "category": "碱性腐蚀品",
                "storage_area": "B-03 固体库",
                "inventory": 350.0,
                "unit": "kg",
                "hazard_level": "中",
                "cas": "1310-73-2",
                "supplier": "启明材料有限公司",
                "updated_at": "2026-06-18 10:05:00",
            },
            {
                "id": "C003",
                "name": "硫酸",
                "category": "酸性腐蚀品",
                "storage_area": "B-01 危化品库",
                "inventory": 640.0,
                "unit": "L",
                "hazard_level": "高",
                "cas": "7664-93-9",
                "supplier": "江南试剂厂",
                "updated_at": "2026-06-18 08:40:00",
            },
            {
                "id": "C004",
                "name": "乙醇",
                "category": "易燃液体",
                "storage_area": "A-02 溶剂库",
                "inventory": 980.0,
                "unit": "L",
                "hazard_level": "中",
                "cas": "64-17-5",
                "supplier": "盛海化学品有限公司",
                "updated_at": "2026-06-17 16:30:00",
            },
            {
                "id": "C005",
                "name": "丙酮",
                "category": "易燃液体",
                "storage_area": "A-02 溶剂库",
                "inventory": 760.0,
                "unit": "L",
                "hazard_level": "高",
                "cas": "67-64-1",
                "supplier": "盛海化学品有限公司",
                "updated_at": "2026-06-17 15:45:00",
            },
            {
                "id": "C006",
                "name": "液氨",
                "category": "压缩气体",
                "storage_area": "C-01 压力容器区",
                "inventory": 2.8,
                "unit": "t",
                "hazard_level": "极高",
                "cas": "7664-41-7",
                "supplier": "中安气体集团",
                "updated_at": "2026-06-18 11:15:00",
            },
        ],
        "parameters": [
            {
                "id": "P001",
                "name": "反应釜温度",
                "area": "A车间",
                "value": 72.4,
                "unit": "℃",
                "low": 50.0,
                "high": 85.0,
                "status": "正常",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:45:00",
            },
            {
                "id": "P002",
                "name": "储罐压力",
                "area": "C罐区",
                "value": 0.62,
                "unit": "MPa",
                "low": 0.30,
                "high": 0.80,
                "status": "正常",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:46:00",
            },
            {
                "id": "P003",
                "name": "VOC浓度",
                "area": "A车间",
                "value": 38.0,
                "unit": "ppm",
                "low": 0.0,
                "high": 80.0,
                "status": "正常",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:47:00",
            },
            {
                "id": "P004",
                "name": "废水pH",
                "area": "D环保站",
                "value": 7.2,
                "unit": "pH",
                "low": 6.0,
                "high": 9.0,
                "status": "正常",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:48:00",
            },
            {
                "id": "P005",
                "name": "冷却水流量",
                "area": "E动力站",
                "value": 118.0,
                "unit": "m³/h",
                "low": 90.0,
                "high": 160.0,
                "status": "正常",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:49:00",
            },
            {
                "id": "P006",
                "name": "液氨储罐液位",
                "area": "C罐区",
                "value": 88.5,
                "unit": "%",
                "low": 30.0,
                "high": 85.0,
                "status": "报警",
                "acknowledged": False,
                "updated_at": "2026-06-18 10:50:00",
            },
        ],
        "work_orders": [
            {
                "id": "WO20260618001",
                "title": "液氨储罐高液位复核",
                "area": "C罐区",
                "priority": "高",
                "status": "处理中",
                "owner": "现场操作员",
                "created_at": "2026-06-18 10:55:00",
                "due_date": "2026-06-19",
                "description": "检查液位计与联锁阀门状态，确认是否需要转移库存。",
            },
            {
                "id": "WO20260617001",
                "title": "A-02 溶剂库通风巡检",
                "area": "A-02 溶剂库",
                "priority": "中",
                "status": "待处理",
                "owner": "现场操作员",
                "created_at": "2026-06-17 14:20:00",
                "due_date": "2026-06-20",
                "description": "完成风机、VOC探头和防静电接地检查。",
            },
            {
                "id": "WO20260616001",
                "title": "废水pH探头标定",
                "area": "D环保站",
                "priority": "低",
                "status": "已完成",
                "owner": "系统管理员",
                "created_at": "2026-06-16 09:00:00",
                "due_date": "2026-06-18",
                "description": "按月度计划完成pH探头两点标定并记录。",
            },
        ],
        "audit_logs": [],
    }
